"""initial_schema

Revision ID: 1d97827c48fe
Revises: 
Create Date: 2026-09-23 23:34:03.173831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d97827c48fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('form_name', sa.String(length=255), nullable=False),
    sa.Column('form_description', sa.Text(), nullable=True),
    sa.Column('form_slug', sa.String(length=255), nullable=False),
    sa.Column('form_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('form_id')
    )
    op.create_index(op.f('ix_forms_form_id'), 'forms', ['form_id'], unique=False)
    op.create_index(op.f('ix_forms_form_slug'), 'forms', ['form_slug'], unique=True)
    op.create_table('form_submissions',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('submission_data', sa.JSON(), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_form_submissions_form_id'), 'form_submissions', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_submission_id'), 'form_submissions', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_submissions_submission_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_form_id'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_forms_form_slug'), table_name='forms')
    op.drop_index(op.f('ix_forms_form_id'), table_name='forms')
    op.drop_table('forms')
    # ### end Alembic commands ###
